### ISSUE TITLE
Doesn't the algorithm perturb the  Y_tags？

### ISSUE THREAD

**Issue by WangKingom** [sisaman/dpgnn#3]
![image](https://user-images.githubusercontent.com/90993951/174420895-bba74301-8f15-44f6-be96-77e120625ad8.png)

**Comment by sisaman** [comment]
y_train and y_val are perturbed, but not y_test as we want to test whether the model can predict the true labels despite being trained on noisy labels.

**Comment by WangKingom** [comment]
Thank you for your prompt reply.
